import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Footer } from "@/components/ui/Footer";
import Navbar from "./components/navbar/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-[#F8F9FD] text-[#1A1A1A]`}
      >
        <div className="min-h-screen flex flex-col">
          {/* Sticky Navbar */}
          <header className="sticky top-0 z-50">
             <Navbar/>
          </header>

          {/* Page Content */}
          <main className="flex-1 p-6 md:p-12 lg:p-16">
             {children}
          </main>
          
          <div className="px-6 md:px-12 lg:px-16 pb-12">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
