import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/navbar/Navbar";
import { Sidebar } from "./components/sidebar/Sidebar";
import { Footer } from "@/components/ui/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-gray-50/50`}
      >
        {/* Fixed Sidebar */}
        <aside className="fixed top-0 left-0 z-30 h-screen w-72 hidden md:block border-r bg-white shadow-sm">
           <Sidebar />
        </aside>

        {/* Main Content Wrapper - Pushed right by sidebar width */}
        <div className="md:ml-72 min-h-screen flex flex-col">
          
          {/* Sticky Navbar */}
          <header className="sticky top-0 z-20 w-full bg-white/80 backdrop-blur-xl border-b border-gray-200/50">
             <Navbar/>
          </header>

          {/* Scrollable Page Content */}
          <main className="flex-1 p-6 md:p-8 space-y-8">
             {children}
          </main>
          
          <div className="p-6 md:p-8 pt-0">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
